base_model: google/gemma-7b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false
seed: 42

datasets:
  - path: /home/dongkeun/axolotl/data/hermes_en-orca-wiki-alpaca-lima.json
    type: sharegpt
dataset_prepared_path:
val_set_size: 0
output_dir: ./gemma-hermes_en-orca-wiki-alpaca-lima
chat_template: chatml

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 64
lora_dropout: 0.0
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: weather_chat
wandb_entity: lklab_kaist
wandb_watch:
wandb_name: gemma-hermes_en-orca-wiki-alpaca-lima
wandb_log_model:

gradient_accumulation_steps: 16
micro_batch_size: 4
num_epochs: 1
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 50
saves_per_epoch: 20
debug:
deepspeed:
weight_decay: 0.01
fsdp:
fsdp_config:
special_tokens: